nombres = ['juan','sebastian','melissa']
print(nombres)
print(type(nombres))
print(nombres[1])
print(nombres[-1])
print(nombres[0:2])
print(len(nombres))
nombres.append('elizabeth')
print(nombres)
nombres.insert(1,'marias')
print(nombres)
nombres.remove('elizabeth')
print(nombres)
nombres.insert(1, 'elizabeth')
print(nombres)
nombres.pop()
print(nombres)
del nombres[3]
print(nombres)
nombres.clear()
print(nombres)
nombres.append('elizabeth')
